### PR TITLE
Add dxva2 hw device

### PR DESCRIPTION
**Pull request by Novacer**
This just adds dxva2 as an option for hardware decoding. Could be an alternative to d3d11 on windows.

Lmk ur thoughts. Feel free to modify/suggest changes.

In terms of actually using this in `qavdemuxer.cpp` perhaps you can look at the supported `AVHWDeviceType`. If it contains `AV_HWDEVICE_TYPE_D3D11VA ` then use that, otherwise fall back to dxva2 or something.

### CODE REVIEW

**Comment by valbok** [comment]
thanks, seems would be needed also qavdemuxer.cpp and interesting can we find a case when there is no d3d11 decoder available but DXVA2 is available?

**Comment by Novacer** [comment]
> thanks, seems would be needed also qavdemuxer.cpp and interesting can we find a case when there is no d3d11 decoder available but DXVA2 is available?

Truth is probably all modern windows computers will have d3d11. But if its a _really_ old system (like ~15+ years old) I think it's possible only dxva2 is available, or d3d11 is available but not all functions are supported.

For example, mozilla browser will fallback to dxva2 on win 7, or if d3d11 is otherwise not available. (https://hg.mozilla.org/mozilla-central/file/tip/dom/media/platforms/wmf/WMFVideoMFTManager.cpp#l199). But they do it because they need to support as many platforms as possible.

Interested to know if you want to support old systems through dxva2, or just not add dxva2 and use software decoding instead. lmk if there's any thoughts.

**Comment by valbok** [comment]
Imo it makes sense only if there is no D3D11 available but DXVA is. But you say it happens only for very old systems. What about Qt version there? Do you use DXVA yourself for reason to support old windows?

**Comment by Novacer** [comment]
> Imo it makes sense only if there is no D3D11 available but DXVA is. But you say it happens only for very old systems. What about Qt version there? Do you use DXVA yourself for reason to support old windows?

I see u support QT 5.12, which oldest supports win 7. I believe win 7 has d3d11 support, so I don't think there's need to use fallback strategy to dxva2. I'm gonna close this for now. LMK otherwise.

**Pull request closed without merging**
