### PR TITLE
Update CMakeLists.txt to support macOS

### LINKED ISSUE #240: can not build on macOS 12 qt5 and ffmpeg 5
FAILED: src/QtAVPlayer/libQtAVPlayer.dylib 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.2 -dynamiclib -Wl,-headerpad_max_install_names -L/usr/local/opt/openssl/lib -L/usr/local/opt/bison/lib -o src/QtAVPlayer/libQtAVPlayer.dylib -install_name @rpath/libQtAVPlayer.dylib src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/QtAVPlayer_autogen/mocs_compilation.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavdemuxer.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavplayer.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavcodec.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavframecodec.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavaudiocodec.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavvideocodec.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavsubtitlecodec.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavpacket.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavvideobuffer_gpu.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavvideobuffer_cpu.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavstreamframe.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavframe.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavvideoframe.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavaudioframe.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavsubtitleframe.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavaudiooutput.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavfilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavvideofilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavaudiofilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavfiltergraph.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavinoutfilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavvideoinputfilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavaudioinputfilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavvideooutputfilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavaudiooutputfilter.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qaviodevice.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavstream.cpp.o src/QtAVPlayer/CMakeFiles/QtAVPlayer.dir/qavhwdevice_videotoolbox.mm.o  /usr/local/lib/libavdevice.dylib  /usr/local/lib/libavfilter.dylib  /usr/local/lib/libavcodec.dylib  /usr/local/lib/libavformat.dylib  /usr/local/lib/libavutil.dylib  /usr/local/lib/libswresample.dylib  /usr/local/lib/libswscale.dylib  /usr/local/opt/qt@5/lib/QtMultimedia.framework/QtMultimedia  -framework  IOSurface  /usr/local/opt/qt@5/lib/QtGui.framework/QtGui  /usr/local/opt/qt@5/lib/QtNetwork.framework/QtNetwork  /usr/local/opt/qt@5/lib/QtCore.framework/QtCore && :
Undefined symbols for architecture x86_64:
  "_CVPixelBufferGetDataSize", referenced from:
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_CVPixelBufferGetIOSurface", referenced from:
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_CVPixelBufferGetPixelFormatType", referenced from:
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_CVPixelBufferGetPlaneCount", referenced from:
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_CVPixelBufferRelease", referenced from:
      QAVHWDevice_VideoToolbox::~QAVHWDevice_VideoToolbox() in qavhwdevice_videotoolbox.mm.o
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_CVPixelBufferRetain", referenced from:
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_MTLCreateSystemDefaultDevice", referenced from:
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
      objc-class-ref in qavhwdevice_videotoolbox.mm.o
  "_objc_msgSend", referenced from:
      VideoBuffer_MTL::handle() const in qavhwdevice_videotoolbox.mm.o
  "_objc_release", referenced from:
      QAVHWDevice_VideoToolbox::~QAVHWDevice_VideoToolbox() in qavhwdevice_videotoolbox.mm.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

### PR DESCRIPTION
**Pull request by leavelet**
adding the CoreVideo.framework to fix #240

### CODE REVIEW

**Comment by leavelet** [comment]
may have some problems. Video can't play.
let me check it tomorrow

**Comment by valbok** [comment]
> may have some problems. Video can't play. let me check it tomorrow

it might be due to https://github.com/valbok/QtAVPlayer/pull/253

**Comment by leavelet** [comment]
> it might be due to #253

Maybe there are some mistakes with MTLTextureHandle?

**Comment by valbok** [comment]
> > it might be due to #253
> 
> Maybe there are some mistakes with MTLTextureHandle?

did you confirm that no vide due to that commit?

**Comment by leavelet** [comment]
> > > it might be due to #253
> > 
> > 
> > Maybe there are some mistakes with MTLTextureHandle?
> 
> did you confirm that no vide due to that commit?

sorry, I am a little busy today, I will reply in a few hours.
(but intuitively, I don't think that problem is caused by that commit.

**Comment by leavelet** [comment]
I tested it. The answer is no.
and there is the output. I am trying to figure out why.
FFmpeg: [h264 @ 0x127e04ce0] hardware accelerator failed to decode picture

**Comment by leavelet** [comment]
and if i use QT_AVPLAYER_NO_HWDEVICE
it says 

`FFmpeg: [swscaler @ 0x118a40000] No accelerated colorspace conversion found from yuv420p to bgra.`

**Comment by leavelet** [comment]
so let's merge this pr and open another iuuse to solve it?

**Comment by leavelet** [comment]
> and if i use QT_AVPLAYER_NO_HWDEVICE it says
> 
> `FFmpeg: [swscaler @ 0x118a40000] No accelerated colorspace conversion found from yuv420p to bgra.`

and the video isn't decoded properly. It is purple without audio

**Comment by valbok** [comment]
> and if i use QT_AVPLAYER_NO_HWDEVICE it says
> 
> `FFmpeg: [swscaler @ 0x118a40000] No accelerated colorspace conversion found from yuv420p to bgra.`

it is about converting acceleration, and not an issue

**Comment by valbok** [comment]
> I tested it. The answer is no. and there is the output. I am trying to figure out why. FFmpeg: [h264 @ 0x127e04ce0] hardware accelerator failed to decode picture

did you try to revert https://github.com/valbok/QtAVPlayer/pull/253/commits/cd440191db09102b87cf8e4289b535656fd33dfd and check?

**Comment by leavelet** [comment]
Yes, if you mean revert that commit only

If you mean revert all the changes after it, let me try it now

The problem is not no audio after turning off hardware acceleration, it becomes the video is not correct

**Pull request merged**
